# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xiaozheng.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 816)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shangchuan = QtWidgets.QPushButton(self.centralwidget)
        self.shangchuan.setGeometry(QtCore.QRect(140, 440, 151, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.shangchuan.setFont(font)
        self.shangchuan.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.shangchuan.setObjectName("shangchuan")
        self.uesr_tongue = QtWidgets.QLabel(self.centralwidget)
        self.uesr_tongue.setGeometry(QtCore.QRect(100, 20, 400, 400))
        self.uesr_tongue.setStyleSheet("\n"
"\n"
"    border:1px solid #717171;\n"
"    border-radius:5px;")
        self.uesr_tongue.setText("")
        self.uesr_tongue.setObjectName("uesr_tongue")
        self.sz_button = QtWidgets.QPushButton(self.centralwidget)
        self.sz_button.setGeometry(QtCore.QRect(580, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.sz_button.setFont(font)
        self.sz_button.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;")
        self.sz_button.setObjectName("sz_button")
        self.ts_button = QtWidgets.QPushButton(self.centralwidget)
        self.ts_button.setGeometry(QtCore.QRect(581, 140, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ts_button.setFont(font)
        self.ts_button.setStyleSheet("    \n"
"    border:1px solid #717171;\n"
"    border-radius:5px;")
        self.ts_button.setObjectName("ts_button")
        self.sz_color = QtWidgets.QLabel(self.centralwidget)
        self.sz_color.setGeometry(QtCore.QRect(750, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sz_color.setFont(font)
        self.sz_color.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.sz_color.setText("")
        self.sz_color.setObjectName("sz_color")
        self.ts_color = QtWidgets.QLabel(self.centralwidget)
        self.ts_color.setGeometry(QtCore.QRect(750, 140, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ts_color.setFont(font)
        self.ts_color.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.ts_color.setText("")
        self.ts_color.setObjectName("ts_color")
        self.lw_button = QtWidgets.QPushButton(self.centralwidget)
        self.lw_button.setGeometry(QtCore.QRect(580, 340, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lw_button.setFont(font)
        self.lw_button.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.lw_button.setObjectName("lw_button")
        self.liewen = QtWidgets.QLabel(self.centralwidget)
        self.liewen.setGeometry(QtCore.QRect(750, 340, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.liewen.setFont(font)
        self.liewen.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.liewen.setText("")
        self.liewen.setObjectName("liewen")
        self.ch_button = QtWidgets.QPushButton(self.centralwidget)
        self.ch_button.setGeometry(QtCore.QRect(580, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ch_button.setFont(font)
        self.ch_button.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.ch_button.setObjectName("ch_button")
        self.chihen = QtWidgets.QLabel(self.centralwidget)
        self.chihen.setGeometry(QtCore.QRect(750, 240, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chihen.setFont(font)
        self.chihen.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.chihen.setText("")
        self.chihen.setObjectName("chihen")
        self.wb_textarea = QtWidgets.QTextBrowser(self.centralwidget)
        self.wb_textarea.setGeometry(QtCore.QRect(100, 500, 891, 291))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.wb_textarea.setFont(font)
        self.wb_textarea.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.wb_textarea.setObjectName("wb_textarea")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(580, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.start.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:skyblue;\n"
"")
        self.start.setObjectName("start")
        self.xiazai = QtWidgets.QPushButton(self.centralwidget)
        self.xiazai.setGeometry(QtCore.QRect(780, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.xiazai.setFont(font)
        self.xiazai.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.xiazai.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:skyblue;\n"
"")
        self.xiazai.setObjectName("xiazai")
        self.paizhao = QtWidgets.QPushButton(self.centralwidget)
        self.paizhao.setGeometry(QtCore.QRect(330, 440, 151, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.paizhao.setFont(font)
        self.paizhao.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.paizhao.setObjectName("paizhao")
        self.uesr_tongue.raise_()
        self.shangchuan.raise_()
        self.sz_button.raise_()
        self.ts_button.raise_()
        self.sz_color.raise_()
        self.ts_color.raise_()
        self.lw_button.raise_()
        self.liewen.raise_()
        self.ch_button.raise_()
        self.chihen.raise_()
        self.wb_textarea.raise_()
        self.start.raise_()
        self.xiazai.raise_()
        self.paizhao.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "舌苔检测系统"))
        self.shangchuan.setText(_translate("MainWindow", "上传舌象"))
        self.sz_button.setText(_translate("MainWindow", "舌色"))
        self.ts_button.setText(_translate("MainWindow", "苔色"))
        self.lw_button.setText(_translate("MainWindow", "裂纹舌"))
        self.ch_button.setText(_translate("MainWindow", "齿痕舌"))
        self.wb_textarea.setPlaceholderText(_translate("MainWindow", "欢迎使用舌苔检测系统！"))
        self.start.setText(_translate("MainWindow", "点击检测"))
        self.xiazai.setText(_translate("MainWindow", "打印报告"))
        self.paizhao.setText(_translate("MainWindow", "打开相机"))
