# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePageWindow(object):
    def setupUi(self, HomePageWindow):
        HomePageWindow.setObjectName("HomePageWindow")
        HomePageWindow.resize(1088, 816)
        HomePageWindow.setBaseSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        HomePageWindow.setFont(font)
        HomePageWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        HomePageWindow.setStyleSheet("background-image:url(E:/HAUT_lunwen/UI/img/background.png);")
        self.centralwidget = QtWidgets.QWidget(HomePageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(870, 740, 181, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:skyblue;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.tongue = QtWidgets.QLabel(self.centralwidget)
        self.tongue.setGeometry(QtCore.QRect(310, 330, 471, 401))
        self.tongue.setStyleSheet("background-image:url(E:/HAUT_lunwen/UI/img/tongue.png);")
        self.tongue.setText("")
        self.tongue.setObjectName("tongue")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 90, 1061, 211))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(44)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        HomePageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomePageWindow)
        QtCore.QMetaObject.connectSlotsByName(HomePageWindow)

    def retranslateUi(self, HomePageWindow):
        _translate = QtCore.QCoreApplication.translate
        HomePageWindow.setWindowTitle(_translate("HomePageWindow", "舌苔检测系统"))
        self.pushButton.setText(_translate("HomePageWindow", "开始使用"))
        self.label.setText(_translate("HomePageWindow", "    基于EfficientNet的舌苔检测系统"))
